name: myai

services:
  searxng-core:
    container_name: searxng-core
    image: docker.io/searxng/searxng:latest
    restart: unless-stopped
    volumes:
      - ./data/searxng-core-config/:/etc/searxng/:Z
      - ./data/searxng-core-data:/var/cache/searxng/
    ports:
      - "0.0.0.0:9000:8080"

  searxng-valkey:
    container_name: searxng-valkey
    image: docker.io/valkey/valkey:9-alpine
    restart: unless-stopped
    command: valkey-server --save 30 1 --loglevel warning
    volumes:
      - ./data/searxng-valkey:/data/

  open-webui:
    container_name: open-webui
    image: ghcr.io/open-webui/open-webui:main
    restart: unless-stopped
    volumes:
      - ./data/open-webui:/app/backend/data
    ports:
      - "0.0.0.0:3000:8080"

  llama-server:
    container_name: llama-server
    image: ghcr.io/ggml-org/llama.cpp:server-rocm
    restart: unless-stopped

    privileged: true
    group_add:
      - video

    devices:
      - /dev/kfd
      - /dev/dri

    ports:
      - "0.0.0.0:8080:8080"

    environment:
      HIP_VISIBLE_DEVICES: "0"
      LLAMA_CACHE: /models
      LLAMA_ARG_MODELS_PRESET: /models.ini

    volumes:
      - ./models:/models
      - ./models.ini:/models.ini:ro

    command:
      - --models-autoload
      - --models-max
      - "1"
      - --no-warmup
      - --host
      - 0.0.0.0
      - --port
      - "8080"
