[*]
kv-unified = true
spec-default = true
no-mmproj = true
jinja = true
fa = on
parallel = 4
; fit = on
; fit-target = 2048
fit = off
cache-type-k = q8_0
cache-type-v = q8_0
batch-size = 1024
ubatch-size = 512

; '--ctx-size' and '--ngl' set to give ~2-3GB VRAM remaining for plenty of overhead

[unsloth/Qwen3.6-27B-GGUF:Q4_K_XL]
alias = qwen3.6-27b
hf = unsloth/Qwen3.6-27B-GGUF:Q4_K_XL
chat-template-kwargs = {"preserve_thinking":true}
temp = 1.0
top-p = 0.95
top-k = 20
min-p = 0.00
ngl = 99
ctx-size = 120000
reasoning-budget = 4096
reasoning-budget-message = ... I am thinking for too long and cannot make a decision. I will now explain the problem to the user and ask them for advice.

[unsloth/Qwen3.6-35B-A3B-GGUF:Q4_K_XL]
alias = qwen3.6-35b-a3b
hf = unsloth/Qwen3.6-35B-A3B-GGUF:Q4_K_XL
chat-template-kwargs = {"preserve_thinking":true}
temp = 1.0
top-p = 0.95
top-k = 20
min-p = 0.00
ngl = 36
ctx-size = 250000

[unsloth/gemma-4-26B-A4B-it-GGUF:Q4_K_XL]
alias = gemma-4-26b-a4b
hf = unsloth/gemma-4-26B-A4B-it-GGUF:Q4_K_XL
temp = 1.0
top-p = 0.95
top-k = 64
ngl = 99
ctx-size = 250000

[unsloth/gemma-4-31b-it-GGUF:Q4_K_XL]
alias = gemma-4-31b
hf = unsloth/gemma-4-31b-it-GGUF:Q4_K_XL
temp = 1.0
top-p = 0.95
top-k = 64
ngl = 99
ctx-size = 40000
