; '--ctx-size' and '--ngl' options shown for two cases:
;   * with desktop: determined with --fit-target 3072 to give 3GB VRAM remaining for plenty of overhead
;   * headless: determined with --fit-target 1024

[*]
kv-unified = true
spec-default = true
no-mmproj = true
mmap = true
jinja = true
fa = on
parallel = 4
cache-type-k = q8_0
cache-type-v = q8_0
batch-size = 1024
ubatch-size = 512
fit = off

;fit = on

; with desktop
;fit-target = 3072

; headless
;fit-target = 1024



[unsloth/Qwen3.6-27B-GGUF:Q4_K_XL]
alias = qwen3.6-27b
hf = unsloth/Qwen3.6-27B-GGUF:Q4_K_XL
chat-template-kwargs = {"preserve_thinking":true}
temp = 1.0
top-p = 0.95
top-k = 20
min-p = 0.00
reasoning-budget = 4096
reasoning-budget-message = ... I am thinking for too long and cannot make a decision. I will now explain the problem to the user and ask them for advice.
ngl = 99

; with desktop
;ctx-size = 99840

; headless
ctx-size = 154624

[unsloth/Qwen3.6-35B-A3B-GGUF:Q4_K_XL]
alias = qwen3.6-35b-a3b
hf = unsloth/Qwen3.6-35B-A3B-GGUF:Q4_K_XL
chat-template-kwargs = {"preserve_thinking":true}
temp = 1.0
top-p = 0.95
top-k = 20
min-p = 0.00

; with desktop
;ngl = 39  ; MoE models can still perform decently with partial offload (here, 1 layer offloaded)
;ctx-size = 69888

; headless
ngl = 99
ctx-size = 142592

[unsloth/gemma-4-26B-A4B-it-GGUF:Q4_K_XL]
alias = gemma-4-26b-a4b
hf = unsloth/gemma-4-26B-A4B-it-GGUF:Q4_K_XL
temp = 1.0
top-p = 0.95
top-k = 64
ngl = 99
ctx-size = 262144

[unsloth/gemma-4-31b-it-GGUF:Q4_K_XL]
alias = gemma-4-31b
hf = unsloth/gemma-4-31b-it-GGUF:Q4_K_XL
temp = 1.0
top-p = 0.95
top-k = 64
ngl = 99

; with desktop
;ctx-size = 28160

; headless
ctx-size = 68608
